### ISSUE TITLE
大佬 你代码有个错误 害得我好苦啊

### ISSUE THREAD

**Issue by lxiaojin** [Peerless-man/vue3-blog#1]

**Comment by lxiaojin** [comment]
博客后台中 .npmrc 代码冲突了 一直用得老的 淘宝镜像 依赖一直下不了

**Comment by mrzym99** [comment]
兄弟不好意思 这份代码我好久没有更新了 抱歉

**Comment by lxiaojin** [comment]
没事 已经处理好了 刚需大佬的分享

**Comment by mrzym99** [comment]
我上传了最新的代码 有需要可以看看 我的gitee上代码是最新的 github没怎么更新 https://gitee.com/mrzym/stable-version-of-blog
